version: "3.0"

services:
  zookeeper:
    container_name: "zookeeper"
    image: docker.io/bitnami/zookeeper:3.9.2
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka0:
    container_name: "kafka0"
    image: docker.io/bitnami/kafka:3.6.2
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER://kafka0:9094, LOCALHOST://kafka0:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka0:9094, LOCALHOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    depends_on:
      - zookeeper
#  kafka1:
#    container_name: "kafka1"
#    image: docker.io/bitnami/kafka:3.6.2
#    ports:
#      - 9093:9093
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: DOCKER://kafka1:9092, LOCALHOST://kafka1:9093
#      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka1:9092, LOCALHOST://localhost:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT, LOCALHOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
#    depends_on:
#      - zookeeper
  kafka-ui:
    container_name: "kafka-ui"
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka0
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9094